/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonatan Grueso Perea
 * @since 14/07/2022
 * @version 1.2
 *
 */
public class InterGestionEmpleados extends javax.swing.JInternalFrame {

    private Empresa empresa;
    private Empleado empleado;
    private Directivo directivo;
    private java.sql.Date sqlPackageDate;
    private SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    private DefaultTableModel modelo;    //Modelo por defecto de la Tabla
    private String fNac;
    private boolean res = false;

    /**
     * Creates new form InterGestionEmpleados
     */
    public InterGestionEmpleados(Empresa empresa) {
        initComponents();

        inhabilitarbotones();
        //inhabilitarCampos();
        txtCategoria.setText("0");
        txtCategoria.setEnabled(false);
        this.empresa = empresa;

        tablaEmpleados.getTableHeader().setReorderingAllowed(false);//Bloquea el movimiento de las columnas, e impide imvertir la información.

        //Permite centrar el JinternalFrame
        int x = JfrPrincipal.escritorio.getWidth() - this.getWidth();
        int y = JfrPrincipal.escritorio.getHeight() - this.getHeight();
        setLocation(x / 2, y / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnHombre = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        boxTID = new javax.swing.JComboBox<>();
        btnMujer = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        txtDoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFechaNac = new com.toedter.calendar.JDateChooser();
        checkDirectivo = new javax.swing.JCheckBox();
        checkSubordinado = new javax.swing.JCheckBox();
        txtSalario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnEliminar2 = new javax.swing.JButton();
        btnActualizar2 = new javax.swing.JButton();
        btnGuardar2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();

        setClosable(true);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Gestión empleados");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        radioGenero.add(btnHombre);
        btnHombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnHombre.setText("Hombre");

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        boxTID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boxTID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "CC", "CE" }));

        radioGenero.add(btnMujer);
        btnMujer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMujer.setText("Mujer");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Fecha nacimiento");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Tipo documento");

        txtTel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("N° documento");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono");

        txtApellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtDir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtDoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Dirección");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Correo eletrónico");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Nombres");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Género");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Apellidos");

        txtFechaNac.setDateFormatString("yyyy-MM-dd");
        txtFechaNac.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFechaNac.setMinSelectableDate(new java.util.Date(-62135747926000L));

        checkDirectivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkDirectivo.setText("Es directivo?");
        checkDirectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkDirectivoMouseClicked(evt);
            }
        });

        checkSubordinado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkSubordinado.setText("Es subordinado?");

        txtSalario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalarioKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Salario Neto");

        txtCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Categoria");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDir))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHombre)
                                .addGap(18, 18, 18)
                                .addComponent(btnMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxTID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalario))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(checkSubordinado)
                                .addGap(18, 18, 18)
                                .addComponent(checkDirectivo)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoria)))))
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxTID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSubordinado)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDirectivo)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tablaEmpleados.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        btnEliminar2.setBackground(new java.awt.Color(153, 102, 0));
        btnEliminar2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEliminar2.setText("Eliminar");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        btnActualizar2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnActualizar2.setText("Modificar");
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });

        btnGuardar2.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGuardar2.setText("Enviar");
        btnGuardar2.setBorderPainted(false);
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });

        btnCancelar2.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelar2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar2.setText("Cancelar");
        btnCancelar2.setBorderPainted(false);
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkDirectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkDirectivoMouseClicked
        
        if (checkDirectivo.isSelected()) {
            txtCategoria.setEnabled(true);
            txtCategoria.setText("");
        } else {
            txtCategoria.setEnabled(false);            
            txtCategoria.setText("0");
        }

    }//GEN-LAST:event_checkDirectivoMouseClicked

    private void txtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyTyped
        char car = evt.getKeyChar();
        //Permite validar que solo se ingresen datos numéricos.
        if((car < '0' || car > '9') && (car != (char)KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {            
            txtSalario.requestFocus();
        }
    }//GEN-LAST:event_txtSalarioKeyTyped

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        
        int fila = tablaEmpleados.getSelectedRow();        
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionadao ningún registro de la tabla");
            btnActualizar2.setEnabled(false);
            btnEliminar2.setEnabled(false);            
        } else {          
            
            habilitarbotones();            
            String TID = (String)tablaEmpleados.getValueAt(fila, 1);
            String doc = (String)tablaEmpleados.getValueAt(fila, 2);
            String nom = (String)tablaEmpleados.getValueAt(fila, 3);
            String apel = (String)tablaEmpleados.getValueAt(fila, 4);            
            String fNac = (String) tablaEmpleados.getValueAt(fila, 5);            
            String genero = (String)tablaEmpleados.getValueAt(fila, 6);                      
            String salario = (String)tablaEmpleados.getValueAt(fila, 8);            
            String subordinado = (String)tablaEmpleados.getValueAt(fila, 9);            
            String categoria = (String)tablaEmpleados.getValueAt(fila, 10);            
            
            
            boxTID.setSelectedItem(TID);
            txtDoc.setText(doc);
            txtNombre.setText(nom);       
            txtApellido.setText(apel); 
            Date date = null;
            try {
                date = new SimpleDateFormat("yyyy-mm-dd").parse(fNac);
            } catch (ParseException ex) {
                Logger.getLogger(InterGestionClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtFechaNac.setDate(date);
            if ("H".equals(genero)) {
                btnHombre.setSelected(true);
            } else {
                btnMujer.setSelected(true);
            }
            
            txtSalario.setText(salario);
            if (subordinado.equals("SI")) { checkSubordinado.setSelected(true); 
            } else { checkSubordinado.setSelected(false); }            
            if (categoria == null || categoria.equals("0")) { 
                checkDirectivo.setSelected(false);
                txtCategoria.setText("0");
            } else { 
                checkDirectivo.setSelected(true);
                txtCategoria.setText(categoria);
            }            
            
        }
        
    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
            habilitarbotonesLimpiar();
            limpiarCampos();
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed

        int id = 0;
        String nombre = txtNombre.getText().toUpperCase();
        String doc = txtDoc.getText();
        String apel = txtApellido.getText().toUpperCase();
        String TID = boxTID.getSelectedItem().toString();        
        char genero = ' ';
        String subor = " ";
        Integer categoria = 0;

        if (checkSubordinado.isSelected()) { subor = "SI"; }
        if (btnHombre.isSelected()) { genero = 'H'; }
        if (btnMujer.isSelected()) { genero = 'M'; }

        // Compara si todos los campos estan vacios
        boolean comp1 = TID.equals("Seleccione...") || nombre.equals("") || apel.equals("") || txtCategoria.getText().equals("");
        boolean comp2 = genero == ' ' || txtFechaNac.getDate() == null || txtSalario.getText().isEmpty();
                            
        if (comp1 || comp2) {
            JOptionPane.showMessageDialog(null, "Faltan campos por diligenciar.");
        } else {
            if (!txtCategoria.getText().equals("0")){
                categoria = Integer.parseInt(txtCategoria.getText());
            }
            //Permite obtener solo la fecha 1900/01/01 desde un JDatechooser
            sqlPackageDate = new java.sql.Date(txtFechaNac.getDate().getTime());
            /// Da formato a la fecha obtenida en la linea anterior
            fNac = df.format(sqlPackageDate);
            Double salario = Double.parseDouble(txtSalario.getText());
            // Determina si la casilla directivo fue seleccionada            
            if (checkDirectivo.isSelected()) {
                directivo = new Directivo(id, TID, doc, nombre, apel, fNac, genero, salario, subor, categoria);
                res = empresa.agregarEmpleado(directivo);
            } else {
                txtCategoria.setEnabled(false);
                empleado = new Empleado(id, TID, doc, nombre, apel, fNac, genero, salario, subor);
                res = empresa.agregarEmpleado(empleado);
            }

            if (res == true) {
                JOptionPane.showMessageDialog(null, "Datos almacenados exitosamente.");
                obtenerListarEmpleados();
                disenoTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error en el proceso de almacenamiento.");
            }
        }
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed

        int id = 0;
        String nombre = txtNombre.getText().toUpperCase();
        String doc = txtDoc.getText();
        String apel = txtApellido.getText().toUpperCase();
        String TID = boxTID.getSelectedItem().toString();        
        char genero = ' ';
        String subor = " ";
        Integer categoria = 0;

        if (checkSubordinado.isSelected()) { subor = "SI"; }
        if (btnHombre.isSelected()) { genero = 'H'; }
        if (btnMujer.isSelected()) { genero = 'M'; }

        // Compara si todos los campos estan vacios
        boolean comp1 = TID.equals("Seleccione...") || nombre.equals("") || apel.equals("") || txtCategoria.getText().equals("");
        boolean comp2 = genero == ' ' || txtFechaNac.getDate() == null || txtSalario.getText().isEmpty();

        int fila = tablaEmpleados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccionar el registro de la tabla");
        } else {
            if (comp1 || comp2) {
                JOptionPane.showMessageDialog(null, "La información no registra ningún cambio.");
            } else {
                 if (!txtCategoria.getText().equals("0")){
                    categoria = Integer.parseInt(txtCategoria.getText());
                }
                //Permite obtener solo la fecha 1900/01/01 desde un JDatechooser
                java.sql.Date sqlPackageDate = new java.sql.Date(txtFechaNac.getDate().getTime());
                /// Da formato a la fecha obtenida en la linea anterior
                String fNac = df.format(sqlPackageDate);
                Double salario = Double.parseDouble(txtSalario.getText());
                // Determina si la casilla directivo fue seleccionada
                if (checkDirectivo.isSelected()) {
                    directivo = new Directivo(id, TID, doc, nombre, apel, fNac, genero, salario, subor, categoria);
                    res = empresa.modificarEmpleado(fila, empleado);
                } else {
                    empleado = new Empleado(id, TID, doc, nombre, apel, fNac, genero, salario, subor);
                    res = empresa.modificarEmpleado(fila, empleado);
                }
                if (res == true) {
                    JOptionPane.showMessageDialog(null, "Datos Actualizados exitosamente.");
                    obtenerListarEmpleados();
                    disenoTabla();
                    limpiarCampos();
                    inhabilitarCampos();
                    habilitarbotones();
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el proceso de almacenamiento.");
                }
            }
        }
    }//GEN-LAST:event_btnActualizar2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed

        inhabilitarCampos();
        int fila = tablaEmpleados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccionar el registro de la tabla");
        } else {           
            int op = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar "
                + "el registro?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                boolean res = empresa.eliminarEmpleado(fila);
                if (res == true) {
                    JOptionPane.showMessageDialog(null, "Registro eliminado exitosamente.");
                    obtenerListarEmpleados();
                    limpiarCampos();
                    habilitarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el proceso de almacenamiento.");
                }
            }
            obtenerListarEmpleados();
            disenoTabla();
            limpiarCampos();
            inhabilitarbotones();
            habilitarCampos();
        }
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    /**
     * *
     * Metodo para listar los clientes en la tabla
     */
    public void obtenerListarEmpleados() {

        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Tid");
        modelo.addColumn("Documento");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Genero");
        modelo.addColumn("Edad");
        modelo.addColumn("Salario Neto");
        modelo.addColumn("Directivo");
        modelo.addColumn("Subordinado");
        modelo.addColumn("Categoria");

        String[] user = new String[12];

        for (int i = 0; i < empresa.getEmpleados().size(); i++) {

            user[0] = String.valueOf(empresa.getEmpleados().get(i).getId());
            user[1] = String.valueOf(empresa.getEmpleados().get(i).getTID());
            user[2] = String.valueOf(empresa.getEmpleados().get(i).getDocumento());
            user[3] = String.valueOf(empresa.getEmpleados().get(i).getNombre());
            user[4] = String.valueOf(empresa.getEmpleados().get(i).getApellidos());
            user[5] = String.valueOf(empresa.getEmpleados().get(i).getFechaNacimiento());
            user[6] = String.valueOf(empresa.getEmpleados().get(i).getGenero());
            user[7] = String.valueOf(empleado.calcularEdad());
            user[8] = String.valueOf(empresa.getEmpleados().get(i).getSalario());
            user[9] = String.valueOf(empresa.getEmpleados().get(i).getSubordinado());
            if (txtCategoria.getText().equals("") || txtCategoria.getText().equals("0")) {
                
            } else {
                user[10] = String.valueOf(directivo.getCategoria());
            }
            modelo.addRow(user);
        }
        tablaEmpleados.setModel(modelo);
    }

    public void habilitarCampos() {
        boxTID.setEnabled(true);
        txtDoc.setEnabled(true);
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtFechaNac.setEnabled(true);
        btnHombre.setEnabled(true);
        btnMujer.setEnabled(true);
    }

    public void inhabilitarCampos() {
        boxTID.setEnabled(false);
        txtDoc.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtFechaNac.setEnabled(false);
        btnHombre.setEnabled(false);
        btnMujer.setEnabled(false);
        txtTel.setEnabled(false);
        txtDir.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCategoria.setEnabled(false);
    }

    public void inhabilitarbotones() {
        btnGuardar2.setEnabled(true);
        btnActualizar2.setEnabled(false);
        btnEliminar2.setEnabled(false);
    }

    public void habilitarbotonesLimpiar() {
        obtenerListarEmpleados();
        disenoTabla();
        btnGuardar2.setEnabled(true);
        btnActualizar2.setEnabled(false);
        btnEliminar2.setEnabled(false);
    }

    public void habilitarbotones() {
        btnGuardar2.setEnabled(false);
        btnActualizar2.setEnabled(true);
        btnEliminar2.setEnabled(true);
    }

    /**
     * Metodo para limpiar pantalla
     */
    public void limpiarCampos() {
        txtDoc.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        boxTID.setSelectedItem("Seleccione...");
        txtTel.setText("");
        txtDir.setText("");
        txtEmail.setText("");
        txtFechaNac.setDate(null);
        radioGenero.clearSelection();
        txtSalario.setText("");
        checkSubordinado.setSelected(false);
        checkDirectivo.setSelected(false);
        txtCategoria.setText("0");
        txtCategoria.setEnabled(false);
    }

    //Método para diseñar las columnas de la tabla Empresa
    void disenoTabla() {
        //Redimensionar el tamaño de las columnas de la tabla.        
        tablaEmpleados.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaEmpleados.getColumnModel().getColumn(0).setMinWidth(0);
        tablaEmpleados.getColumnModel().getColumn(0).setPreferredWidth(0);
        //.
        tablaEmpleados.getColumnModel().getColumn(1).setMaxWidth(30);
        tablaEmpleados.getColumnModel().getColumn(1).setMinWidth(30);
        tablaEmpleados.getColumnModel().getColumn(1).setPreferredWidth(30);
        //.
        tablaEmpleados.getColumnModel().getColumn(2).setMaxWidth(120);
        tablaEmpleados.getColumnModel().getColumn(2).setMinWidth(120);
        tablaEmpleados.getColumnModel().getColumn(2).setPreferredWidth(120);
        //.De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(3).setMaxWidth(155);
        tablaEmpleados.getColumnModel().getColumn(3).setMinWidth(155);
        tablaEmpleados.getColumnModel().getColumn(3).setPreferredWidth(155);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(4).setMaxWidth(155);
        tablaEmpleados.getColumnModel().getColumn(4).setMinWidth(155);
        tablaEmpleados.getColumnModel().getColumn(4).setPreferredWidth(155);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(5).setMaxWidth(120);
        tablaEmpleados.getColumnModel().getColumn(5).setMinWidth(120);
        tablaEmpleados.getColumnModel().getColumn(5).setPreferredWidth(120);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(6).setMaxWidth(60);
        tablaEmpleados.getColumnModel().getColumn(6).setMinWidth(60);
        tablaEmpleados.getColumnModel().getColumn(6).setPreferredWidth(60);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(7).setMaxWidth(50);
        tablaEmpleados.getColumnModel().getColumn(7).setMinWidth(50);
        tablaEmpleados.getColumnModel().getColumn(7).setPreferredWidth(50);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(8).setMaxWidth(130);
        tablaEmpleados.getColumnModel().getColumn(8).setMinWidth(130);
        tablaEmpleados.getColumnModel().getColumn(8).setPreferredWidth(130);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(9).setMaxWidth(0);
        tablaEmpleados.getColumnModel().getColumn(9).setMinWidth(0);
        tablaEmpleados.getColumnModel().getColumn(9).setPreferredWidth(0);
        //De este modo se oculta la columna 
        tablaEmpleados.getColumnModel().getColumn(9).setMaxWidth(0);
        tablaEmpleados.getColumnModel().getColumn(9).setMinWidth(0);
        tablaEmpleados.getColumnModel().getColumn(9).setPreferredWidth(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTID;
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JRadioButton btnHombre;
    private javax.swing.JRadioButton btnMujer;
    private javax.swing.JCheckBox checkDirectivo;
    private javax.swing.JCheckBox checkSubordinado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.ButtonGroup radioGenero;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtEmail;
    private com.toedter.calendar.JDateChooser txtFechaNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
