/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Empresa;
import static View.JfrPrincipal.escritorio;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Q-USER
 */
public class InterListarEmpresa extends javax.swing.JInternalFrame {

    private Empresa empresa;
    DefaultTableModel modelo;    //Modelo por defecto de la Tabla

    /**
     * Creates new form InternalFrameListarEmpresa
     */
//    public InterListarEmpresa() {
//        initComponents();
//
//        inhabilitarbotones();
//        
//        //listar();
//        //disenoTabla();
//        tablaEmpresa.getTableHeader().setReorderingAllowed(false);//Bloquea el movimiento de las columnas, e impide imvertir la información.
//
//        //Permite centrar el JinternalFrame
//        int x = JfrPrincipal.escritorio.getWidth() - this.getWidth();
//        int y = JfrPrincipal.escritorio.getHeight() - this.getHeight();
//        setLocation(x / 2, y / 2);
//    }

    public InterListarEmpresa(Empresa empresa) {
        initComponents();
        this.empresa = empresa;

        inhabilitarbotones();

        tablaEmpresa.getTableHeader().setReorderingAllowed(false);//Bloquea el movimiento de las columnas, e impide imvertir la información.

        //Permite centrar el JinternalFrame
        int x = JfrPrincipal.escritorio.getWidth() - this.getWidth();
        int y = JfrPrincipal.escritorio.getHeight() - this.getHeight();
        setLocation(x / 2, y / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtActEconomica = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpresa = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Información empresa");

        btnActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 153, 0));
        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAgregar.setText("Enviar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("NIT");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Razón social");

        txtNIT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Correo Electrónico");

        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");

        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Dirección");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Actividad económica");

        txtActEconomica.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNIT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtActEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla"));

        tablaEmpresa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Razón social", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpresa.setEditingColumn(0);
        tablaEmpresa.setEditingRow(0);
        tablaEmpresa.setRowHeight(22);
        tablaEmpresa.getTableHeader().setReorderingAllowed(false);
        tablaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpresa);
        if (tablaEmpresa.getColumnModel().getColumnCount() > 0) {
            tablaEmpresa.getColumnModel().getColumn(0).setResizable(false);
            tablaEmpresa.getColumnModel().getColumn(1).setResizable(false);
            tablaEmpresa.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVer.setText("Ver más...");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        String nombre = txtNombre.getText().toUpperCase();
        String NIT = txtNIT.getText();
        String tel = txtTelefono.getText();
        String dir = txtDireccion.getText().toUpperCase();
        String email = txtEmail.getText();
        String actEconomica = txtActEconomica.getText().toUpperCase();

        // Compara si todos los campos son iguales a los existentes
        boolean comp1 = nombre.equals("") || NIT.equals("") || actEconomica.equals("");
        boolean comp2 = tel.equals("") || dir.equals("") || email.equals("");

        int fila = tablaEmpresa.getSelectedRow();
        if (fila == -1) {

            JOptionPane.showMessageDialog(null, "Seleccionar el registro de la tabla");
        } else {
            if (comp1 || comp2) {
                JOptionPane.showMessageDialog(null, "La información no registra ningún cambio.");
            } else {                
                empresa = new Empresa(nombre, NIT, tel, dir, email, actEconomica);
                limpiarTabla(modelo);
                listar();
                disenoTabla();
                JOptionPane.showMessageDialog(null, "Datos actualizados exitosamente.");
                limpiarCampos();
                inhabilitarCampos();
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txtNombre.getText().toUpperCase();
        String NIT = txtNIT.getText();
        String tel = txtTelefono.getText();
        String dir = txtDireccion.getText().toUpperCase();
        String email = txtEmail.getText();
        String actEconomica = txtActEconomica.getText().toUpperCase();

        // Compara si todos los campos estan vacios
        boolean comp1 = nombre.equals("") || NIT.equals("") || actEconomica.equals("");
        boolean comp2 = tel.equals("") || dir.equals("") || email.equals("");

        if (comp1 || comp2) {
            JOptionPane.showMessageDialog(null, "Debe diligenciar todos los campos.");
        } else {            
            empresa = new Empresa(nombre, NIT, tel, dir, email, actEconomica);
            JOptionPane.showMessageDialog(null, "Datos almacenados exitosamente.");
            listar();
            disenoTabla();
            habilitarbotones();
            limpiarCampos();
            inhabilitarCampos();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        InterVerDatosEmpresa ventana = new InterVerDatosEmpresa(empresa);
        escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_btnVerActionPerformed

    private void tablaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpresaMouseClicked
        int fila = tablaEmpresa.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccionar el registro de la tabla");
            btnActualizar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnVer.setEnabled(false);
        } else {
            habilitarCampos();
            String nom = (String) tablaEmpresa.getValueAt(fila, 0);
            String NIT = (String) tablaEmpresa.getValueAt(fila, 1);
            String tel = (String) tablaEmpresa.getValueAt(fila, 2);
            String dir = (String) tablaEmpresa.getValueAt(fila, 3);
            String email = (String) tablaEmpresa.getValueAt(fila, 4);
            String actEcon = (String) tablaEmpresa.getValueAt(fila, 5);

            txtNombre.setText(nom);
            txtNIT.setText(NIT);
            txtTelefono.setText(tel);
            txtDireccion.setText(dir);
            txtEmail.setText(email);
            txtActEconomica.setText(actEcon);
        }
    }//GEN-LAST:event_tablaEmpresaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaEmpresa.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar el registro de la tabla");

        } else {
            inhabilitarCampos();
            int op = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el registro?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Registro eliminado exitosamente.");
                limpiarTabla(modelo);
                limpiarCampos();
                habilitarCampos();
            } else {                
                listar();
                disenoTabla();
                limpiarCampos();
                inhabilitarCampos();
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
       char car = evt.getKeyChar();
       //Permite validar que solo se ingresen datos numéricos.
       if((car < '0' || car > '9') && (car != (char)KeyEvent.VK_BACK_SPACE) && (car != (char)KeyEvent.VK_DELETE)){
           evt.consume();
           JOptionPane.showMessageDialog(null, "Solo se admiten números. Verifique su información.");           
       }  
    }//GEN-LAST:event_txtNITKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char car = evt.getKeyChar();
       //Permite validar que solo se ingresen datos numéricos.
       if((car < '0' || car > '9') && (car != (char)KeyEvent.VK_BACK_SPACE) && (car != (char)KeyEvent.VK_DELETE)){
           evt.consume();
           JOptionPane.showMessageDialog(null, "Solo se admiten números. Verifique su información.");           
       } 
    }//GEN-LAST:event_txtTelefonoKeyTyped

    public void habilitarCampos() {
        txtNombre.setEnabled(true);
        txtNIT.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtEmail.setEnabled(true);
        txtActEconomica.setEnabled(true);
    }

    public void inhabilitarCampos() {
        txtNombre.setEnabled(false);
        txtNIT.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtEmail.setEnabled(false);
        txtActEconomica.setEnabled(false);
    }

    public void limpiarCampos() {
        txtNombre.setText("");
        txtNIT.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtActEconomica.setText("");
    }

    public void inhabilitarbotones() {
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnVer.setEnabled(false);
    }

    public void habilitarbotones() {
        btnAgregar.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnVer.setEnabled(true);
    }

    public void listar() {

        modelo = new DefaultTableModel();
        modelo.addColumn("Razón social");
        modelo.addColumn("NIT");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Dirección");
        modelo.addColumn("Correo electrónico");
        modelo.addColumn("Actividad Económica");

        String[] user = new String[6];

        user[0] = empresa.getNombre();
        user[1] = empresa.getNIT();
        user[2] = empresa.getTelfono();
        user[3] = empresa.getDireccion();
        user[4] = empresa.getEmail();
        user[5] = empresa.getActEconomica();

        modelo.addRow(user);

        tablaEmpresa.setModel(modelo);
    }

    //Método para limpiar refrescar los datos de la tabla
    void limpiarTabla(DefaultTableModel modelo) {
        while (tablaEmpresa.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    //Método para diseñar las columnas de la tabla Empresa
    void disenoTabla() {
        //Redimensionar el tamaño de las columnas de la tabla.        
        tablaEmpresa.getColumnModel().getColumn(0).setMaxWidth(240);
        tablaEmpresa.getColumnModel().getColumn(0).setMinWidth(240);
        tablaEmpresa.getColumnModel().getColumn(0).setPreferredWidth(240);
        //.
        tablaEmpresa.getColumnModel().getColumn(1).setMaxWidth(180);
        tablaEmpresa.getColumnModel().getColumn(1).setMinWidth(180);
        tablaEmpresa.getColumnModel().getColumn(1).setPreferredWidth(180);
        //.
        tablaEmpresa.getColumnModel().getColumn(2).setMaxWidth(170);
        tablaEmpresa.getColumnModel().getColumn(2).setMinWidth(170);
        tablaEmpresa.getColumnModel().getColumn(2).setPreferredWidth(170);
        //.De este modo se oculta la columna 
        tablaEmpresa.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaEmpresa.getColumnModel().getColumn(3).setMinWidth(0);
        tablaEmpresa.getColumnModel().getColumn(3).setPreferredWidth(0);
        //De este modo se oculta la columna 
        tablaEmpresa.getColumnModel().getColumn(4).setMaxWidth(0);
        tablaEmpresa.getColumnModel().getColumn(4).setMinWidth(0);
        tablaEmpresa.getColumnModel().getColumn(4).setPreferredWidth(0);
        //De este modo se oculta la columna 
        tablaEmpresa.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaEmpresa.getColumnModel().getColumn(5).setMinWidth(0);
        tablaEmpresa.getColumnModel().getColumn(5).setPreferredWidth(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable tablaEmpresa;
    public static javax.swing.JTextField txtActEconomica;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNIT;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
